<a href="https://colab.research.google.com/github/brunaopdejesus/redesNeurais/blob/main/TIAF2023_RN_Aula04_Treinamento_do_Perceptron_ALUNO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

FIAP - Redes Neurais Artificiais, Deep Learning e Algoritmos Genéticos 

# Aula 04 - Treinamento do Perceptron

Lembrando do que vimos na matéria de _Machine Learning_, quando desenvolvemos modelos preditivos temos 2 fases: 
- **treinamento** : construção do modelo
- **teste** : uso do modelo construído

Na última aula, nós usamos uma rede "pronta" para predizer se uma faculdade era uma boa escolha ou não (modelo de classificação) ou prever um score de cada faculdade para criar um ranking (modelo de regressão).

Note que os pesos já foram fornecidos, ou seja, o modelo já estava "treinado": 

```python
pesos = [ 0.10, 0.05, 0.05, 0.2, 0.25, 0.3, 0.05 ]
```

Mas e se os pesos não fossem dados? Como poderíamos encontrar os melhores pesos para o problema? Daí surge o **treinamento dos modelos**, ou seja, encontrar os pesos adequados para modelar o problema. 

## Treinamento do Perceptron 

Aprendendo os melhores pesos para modelar o problema. 


1. Conhecer os dados de entrada e saída (labels)
2. Inicializar os pesos (ex: valores aleatórios) 
3. Para todo dado de treinamento: 
    - Calcular as predições com os pesos correntes e as entradas e a função de ativação 
    - Calcular os erros das predições em relação às entradas 
    - Para cada peso: 
        - Atualizá-lo mediante o erro calculado (com a fórmula: pesos(n+1) = pesos(n) + (entrada * erro * taxaAprendizagem))
4. Repetir passos a partir do #3 enquanto “erro != zero”


In [8]:
import numpy as np
entradas = np.array([[0, 0],
                     [0, 1],
                     [1, 0],
                     [1, 1]])
saidas = np.array( [0, 0, 0, 1] )
pesos = np.array( [0.5, -0.2] )   # Experimente alterar os pesos iniciais 
taxaAprendizagem = 0.2           # Varie este valor e veja o reflexo na saída

In [6]:
def funcao_ativacao(u):
  if u >= 1:
    return 1
  else:
    return 0

def calcula_saida(linha):
  soma = linha.dot(pesos)  # dot é uma função do numpy que multiplica e soma os valores de cada vetor (soma ponderada)
  return funcao_ativacao(soma)

# função para treinar o perceptron e achar os pesos
def treinar():
  erroTotal = 1  # força a entrada no while, pode ser qualquer número diferente de 0

  while erroTotal != 0:
    erroTotal = 0  # erro 0 porque não teve nenhuma previsão ainda
    for i in range(len(saidas)):
      saidaCalculada = calcula_saida(entradas[i]) # i é cada linha do array, cada exemplo de treinamento. [0,0]; [0,1]; [1,0]; [1,1]
      erro = saidas[i] - saidaCalculada # LABEL ESPERADO - LABEL PREDITO | saidas sao os labels
      erroTotal = erroTotal + erro # atualizo o valor de erroTotal
      print(f"\tDado: {i}") # marca em qual linha está

      for j in range(len(pesos)):
        pesos[j] = pesos[j] + (taxaAprendizagem * erro * entradas[i][j]) # linhas e colunas
        print(f"\t\tPeso atualizado {j}: {pesos[j]}")
    
    print(f"---> Total de erros: {erroTotal}\n")


In [2]:
entradas # pega o array inteiro  

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [3]:
entradas[3] # pega toda a linha 3

array([1, 1])

In [4]:
entradas[3][1] # pega o segundo elemento da linha 3

1

In [9]:
treinar()

	Dado: 0
		Peso atualizado 0: 0.5
		Peso atualizado 1: -0.2
	Dado: 1
		Peso atualizado 0: 0.5
		Peso atualizado 1: -0.2
	Dado: 2
		Peso atualizado 0: 0.5
		Peso atualizado 1: -0.2
	Dado: 3
		Peso atualizado 0: 0.7
		Peso atualizado 1: 0.0
---> Total de erros: 1

	Dado: 0
		Peso atualizado 0: 0.7
		Peso atualizado 1: 0.0
	Dado: 1
		Peso atualizado 0: 0.7
		Peso atualizado 1: 0.0
	Dado: 2
		Peso atualizado 0: 0.7
		Peso atualizado 1: 0.0
	Dado: 3
		Peso atualizado 0: 0.8999999999999999
		Peso atualizado 1: 0.2
---> Total de erros: 1

	Dado: 0
		Peso atualizado 0: 0.8999999999999999
		Peso atualizado 1: 0.2
	Dado: 1
		Peso atualizado 0: 0.8999999999999999
		Peso atualizado 1: 0.2
	Dado: 2
		Peso atualizado 0: 0.8999999999999999
		Peso atualizado 1: 0.2
	Dado: 3
		Peso atualizado 0: 0.8999999999999999
		Peso atualizado 1: 0.2
---> Total de erros: 0



In [10]:
pesos

array([0.9, 0.2])

## Para casa

Altere os valores dos pesos iniciais e da taxa de aprendizagem e observe o impacto no treinamento da rede. 

Note que eventualmente você pode chegar em uma configuração que a rede não converge para os pesos adequados (ou seja, o laço `while` continua a rodar infinitamente. Se isso ocorrer, pare a execução no botão STOP (interrupt the kernel), ou vá em Kernel > Restart. 